model:
  name: "BertG2P"
  embedding_dim: 128
  num_heads: 8
  num_layers: 2
  feedforward_dim: 128
  max_len: 32
  vocab_size: 32
training:
  batch_size: 32
  epochs: 5
  learning_rate: 0.00001
  weight_decay: 0.01
  validation_split: 0.1
  use_tensorboard: true
data:
  train_csv: "data/raw/train.csv"
  val_csv: "data/raw/val.csv"
  test_csv: "data/raw/test.csv"
  phoneme_dict: "data/dictionary/ind_phoneme_dict.csv"
  processed_train: "data/processed/train.pkl"
  processed_val: "data/processed/val.pkl"
export:
  onnx_model_path: "checkpoints/bert_g2p.onnx"
